#* VERSION SLIM DE PYTHON => ES MAS LIGERA PARA PRODUCION
FROM python:3.11-slim

#* EVITAR QUE PYTHON GENERE ARCHIVOS .pyc Y BUFER EN LA SALIDA
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

#* ESTABLECER EL DIRECTORIO DE TRABAJO DENTRO DEL CONTENEDOR
WORKDIR /app

#* AHORA SI INSTALAR LAS DEPENDENCIAS DEL SISTEMA
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    pkg-config \
    default-libmysqlclient-dev \
    && rm -rf /var/lib/apt/lists/*

#* COPIAR E INSTALAR LAS DEPENDENCIAS DE PYTHON 
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

#* COPIAR TODO EL CODIGO DEL PROYECTO AL DIRECTORIO DE TRABAJO
COPY . .

#* EXPONER EL PUERTO 8006 PARA QUE SEA ACCESIBLE DESDE AFUERA DEL CONTENDOR
EXPOSE 8006

#* COMANDO POR DEFECTO
CMD ["python", "manage.py", "runserver", "0.0.0.0:8006"]
