# Generated by Django 5.1.4 on 2025-08-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('correct_answers', models.IntegerField(blank=True, null=True)),
                ('validation_success', models.BooleanField(blank=True, null=True)),
                ('user_info', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
