# Generated by Django 5.2.5 on 2025-08-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validationrecord',
            name='correct_answers',
        ),
        migrations.AddField(
            model_name='validationrecord',
            name='fecha_expedicion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='validationrecord',
            name='user_answers',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
